export const dailyVerses = [
  { arabic: 'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ', text: '"Dan apabila hamba-hamba-Ku bertanya kepadamu tentang Aku, maka (jawablah), bahwasanya Aku adalah dekat."', source: 'QS. Al-Baqarah 2:186' },
  { arabic: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا', text: '"Sesungguhnya sesudah kesulitan itu ada kemudahan."', source: 'QS. Al-Insyirah 94:6' },
  { arabic: 'وَتَوَكَّلْ عَلَى اللَّهِ وَكَفَىٰ بِاللَّهِ وَكِيلًا', text: '"Dan bertawakallah kepada Allah. Dan cukuplah Allah sebagai pemelihara."', source: 'QS. Al-Ahzab 33:3' },
  { arabic: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونَ', text: '"Maka ingatlah kepada-Ku, niscaya Aku akan mengingat kamu."', source: 'QS. Al-Baqarah 2:152' },
  { arabic: 'حَسْبِيَ اللَّهُ لَا إِلَـٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ', text: '"Cukuplah Allah bagiku; tidak ada Tuhan selain Dia. Hanya kepada-Nya aku bertawakal."', source: 'QS. At-Taubah 9:129' },
  { arabic: 'وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ', text: '"Dan Tuhanmu berfirman: Berdoalah kepada-Ku, niscaya akan Kuperkenankan bagimu."', source: 'QS. Ghafir 40:60' },
  { arabic: 'يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ', text: '"Hai orang-orang yang beriman, jadikanlah sabar dan shalat sebagai penolongmu."', source: 'QS. Al-Baqarah 2:153' },
  { arabic: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا', text: '"Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya."', source: 'QS. Al-Baqarah 2:286' },
  { arabic: 'إِنَّ اللَّهَ مَعَ الصَّابِرِينَ', text: '"Sesungguhnya Allah beserta orang-orang yang sabar."', source: 'QS. Al-Baqarah 2:153' },
  { arabic: 'وَلَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ', text: '"Dan janganlah kamu berputus asa dari rahmat Allah."', source: 'QS. Az-Zumar 39:53' },
  { arabic: 'وَمَنْ يَتَّقِ اللَّهَ يَجْعَلْ لَهُ مَخْرَجًا', text: '"Barangsiapa bertakwa kepada Allah niscaya Dia akan membukakan jalan keluar baginya."', source: 'QS. At-Talaq 65:2' },
  { arabic: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا', text: '"Sesungguhnya bersama kesulitan ada kemudahan."', source: 'QS. Al-Insyirah 94:5' },
  { arabic: 'وَهُوَ مَعَكُمْ أَيْنَ مَا كُنْتُمْ', text: '"Dan Dia bersama kamu di mana saja kamu berada."', source: 'QS. Al-Hadid 57:4' },
  { arabic: 'هُوَ الَّذِي أَنْزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ', text: '"Dia-lah yang menurunkan ketenangan ke dalam hati orang-orang mukmin."', source: 'QS. Al-Fath 48:4' },
];
